### ISSUE TITLE
Create a V5Serial and a V5RS485 class for ROS communications

### ISSUE THREAD

**Issue by NathanDuPont** [msoe-vex/ChangeUp#30]
Combine the classes from the noetic-devel and rs-485 branches into the noetic-devel branch, with two classes in place of the V5Hardware class. These two classes will each contain separate logic for ROS communications, with the V5Serial class containing the code from V5Hardware in the noetic-devel branch, and the V%RS485 class containing the code from the V5Hardware class in the rs-485 branch

**Comment by NathanDuPont** [comment]
View tasks in the linked project

**Comment by AndrewKempen** [comment]
To-Do:
- [ ] Test PCB with old RS-485 class
- [ ] Rename V5Serial and RS-485 hardware.h implementations
- [ ] Test both V5Serial and RS-485 implementations
